// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_Calculate.Data;

#nullable disable

namespace _10_Calculator.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    [Migration("20250515094019_123")]
    partial class _123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Calculator.Data.DataInputVariant", b =>
                {
                    b.Property<int>("ID_DataInputVariant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Operand_1")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Operand_2")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Type_operation")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("ID_DataInputVariant");

                    b.ToTable("DataInputVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
